apiVersion: apps/v1
kind: Deployment
metadata:
  name: train-ticket-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: train-ticket
  template:
    metadata:
      labels:
        app: train-ticket
    spec:
      containers:
        - name: train-ticket-container
          image: rajkumarnanchari/train-ticket-app
          ports:
            - containerPort: 5000
